# Generated by Django 4.1.7 on 2023-02-17 02:57

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('id', models.SlugField(max_length=255, primary_key=True, serialize=False)),
                ('gbfs_href', models.URLField(max_length=300)),
                ('href', models.CharField(max_length=255)),
                ('company', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=10)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('empty_slots', models.IntegerField(default=0)),
                ('free_bikes', models.IntegerField(default=0)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('latitude', models.DecimalField(decimal_places=9, default=0, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=9, default=0, max_digits=12)),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_station', to='citybike.network')),
            ],
        ),
        migrations.CreateModel(
            name='StationExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('altitude', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('ebikes', models.IntegerField(default=0)),
                ('has_ebikes', models.BooleanField(default=False)),
                ('last_updated', models.IntegerField(default=0)),
                ('normal_bikes', models.IntegerField(default=0)),
                ('payment', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('payment_terminal', models.BooleanField(default=False)),
                ('post_code', models.CharField(blank=True, max_length=255, null=True)),
                ('renting', models.IntegerField(default=0)),
                ('returning', models.IntegerField(default=0)),
                ('slots', models.IntegerField(default=0)),
                ('uid', models.CharField(max_length=255, unique=True)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='station_extra', to='citybike.station')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=12)),
                ('latitude', models.DecimalField(decimal_places=9, default=0, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=9, default=0, max_digits=12)),
                ('network', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='network_location', to='citybike.network')),
            ],
        ),
    ]
