# Generated by Django 4.1.7 on 2023-02-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citybike', '0002_rename_last_update_stationextra_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationextra',
            name='post_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
