# Generated by Django 4.1.7 on 2023-02-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citybike', '0003_alter_stationextra_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='station',
            name='latitude',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='station',
            name='longitude',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stationextra',
            name='altitude',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
    ]
