# Generated by Django 4.1.7 on 2023-02-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('project_type', models.CharField(max_length=64)),
                ('region', models.CharField(max_length=64)),
                ('typology', models.CharField(max_length=64)),
                ('titular', models.CharField(max_length=255)),
                ('investment', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(max_length=122)),
                ('map', models.URLField(default='', max_length=255)),
            ],
        ),
    ]
