# Generated by Django 4.1.7 on 2023-02-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraping', '0003_alter_project_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
