# Generated by Django 4.1.7 on 2023-02-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraping', '0004_alter_project_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=555),
        ),
    ]
